name: Sync Fork

on:
  schedule:
    # Schedule the workflow to run every day. You can adjust the cron syntax as needed.
    - cron: '0 0 * * *'  # midnight every day
  workflow_dispatch:
    # This allows you to manually trigger the workflow from the Actions tab on GitHub.

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: master

    - name: Sync with Upstream
      run: |
        git config --global user.name 'Nicholas Colyer'
        git config --global user.email 'ncolyer+big-list-of-naughty-strings@gmail.com'
        git remote add upstream https://github.com/minimaxir/big-list-of-naughty-strings.git
        git fetch upstream
        git checkout master
        git merge upstream/master --allow-unrelated-histories
        git push
